const baseRedirects = [
  // //post-sitemap.xml
  // { source: '/ssa-rinjani', destination: '/', permanent: true },
  // { source: '/lets-meet-up-with-sb-acoustics', destination: '/', permanent: true },
  // { source: '/iheac-2019', destination: '/', permanent: true },
  // { source: '/munich-high-end-2019', destination: '/', permanent: true },
  // { source: '/munich-high-end-2018', destination: '/', permanent: true },
  // { source: '/iheac-2017', destination: '/', permanent: true },
  // { source: '/munich-high-end-2017', destination: '/', permanent: true },
  // { source: '/idldc-2017', destination: '/', permanent: true },
  // { source: '/munich-high-end-2016', destination: '/', permanent: true },
  // { source: '/munich-high-end-2015', destination: '/', permanent: true },
  // { source: '/factory-tour-sinar-baja-electric-and-sb-acoustics', destination: '/', permanent: true },
  // { source: '/iheac-2018', destination: '/', permanent: true },

  //page-sitemap.xml
  { source: '/technical-notes', destination: '/technical', permanent: true },
  { source: '/about', destination: '/aboutus', permanent: true },
  { source: '/links', destination: '/technical', permanent: true },
  { source: '/subscribe', destination: '/newsletter', permanent: true },
  { source: '/subscribe-old', destination: '/newsletter', permanent: true },
  // { source: '/logo', destination: '/', permanent: true },
  // { source: '/privacy-policy', destination: '/', permanent: true },
  // { source: '/no-access', destination: '/', permanent: true },
  { source: '/product', destination: '/products', permanent: true },

  // //category-sitemap.xml
  // { source: '/category/news', destination: '/', permanent: true },
  // { source: '/category/events', destination: '/', permanent: true },

  //product_cat-sitemap.xml
  { source: '/product-category/drivers/tweeters', destination: '/drivers/tweeters', permanent: true },
  { source: '/product-category/drivers', destination: '/drivers', permanent: true },
  { source: '/product-category/drivers/widebanders', destination: '/drivers/widebanders', permanent: true },
  { source: '/product-category/drivers/midranges', destination: '/drivers/midranges', permanent: true },
  { source: '/product-category/drivers/midwoofers', destination: '/drivers/midwoofers', permanent: true },
  { source: '/product-category/drivers/passive-radiators', destination: '/drivers/passive-radiators', permanent: true },
  { source: '/product-category/drivers/subwoofers', destination: '/drivers/subwoofers', permanent: true },
  { source: '/product-category/drivers/woofers', destination: '/drivers/woofers', permanent: true },
  { source: '/product-category/drivers/tweeters/dome-tweeters', destination: '/drivers/tweeters/dome-tweeter', permanent: true },
  { source: '/product-category/drivers/tweeters/ring-radiators', destination: '/drivers/tweeters/ring-radiators', permanent: true },
  { source: '/product-category/drivers/tweeters/satori-tweeters', destination: '/drivers/tweeters/satori-tweeters', permanent: true },
  { source: '/product-category/drivers/midranges/nrx-midranges', destination: '/drivers/midranges/nrx-midranges', permanent: true },
  { source: '/product-category/drivers/midranges/satori-midranges', destination: '/drivers/midranges/satori-midranges', permanent: true },
  { source: '/product-category/drivers/midwoofers/cac-midwoofers', destination: '/drivers/midwoofers/cac-midwoofers', permanent: true },
  { source: '/product-category/drivers/midwoofers/crc-midwoofers', destination: '/drivers/midwoofers/crc-midwoofers', permanent: true },
  { source: '/product-category/drivers/midwoofers/mfc-midwoofers', destination: '/drivers/midwoofers/mfc-midwoofers', permanent: true },
  { source: '/product-category/drivers/midwoofers/nac-midwoofers', destination: '/drivers/midwoofers/nbac-midwoofers', permanent: true },
  { source: '/product-category/drivers/midwoofers/nrx-midwoofers', destination: '/drivers/midwoofers/nrx-midwoofers', permanent: true },
  { source: '/product-category/drivers/midwoofers/pac-midwoofers', destination: '/drivers/midwoofers/pac-midwoofers', permanent: true },
  { source: '/product-category/drivers/midwoofers/pfc-midwoofers', destination: '/drivers/midwoofers/pfcr-midwoofers', permanent: true },
  { source: '/product-category/drivers/midwoofers/satori-midwoofers', destination: '/drivers/midwoofers/satori-midwoofers', permanent: true },
  { source: '/product-category/drivers/woofers/pfc-woofers', destination: '/drivers/woofers/pfcr-woofers', permanent: true },
  { source: '/product-category/drivers/woofers/nrx-woofers', destination: '/drivers/woofers/nrx-woofers', permanent: true },
  { source: '/product-category/drivers/woofers/nac-woofers', destination: '/drivers/woofers/nbac-woofers', permanent: true },
  { source: '/product-category/drivers/shallow-subwoofers', destination: '/drivers/shallow-subwoofers', permanent: true },
  { source: '/product-category/drivers/woofers/satori-woofers', destination: '/drivers/woofers/satori-woofers', permanent: true },
  { source: '/product-category/kits/sb-acoustics-kits', destination: '/kits/sb-acoustics-kits', permanent: true },
  { source: '/product-category/new-products', destination: '/new-products', permanent: true },
  { source: '/product-category/kits/open-source-kits', destination: '/kits/open-source-kits', permanent: true },
  { source: '/product-category/drivers/oem', destination: '/drivers/oem', permanent: true },
  { source: '/product-category/drivers/midwoofers/sfcr-midwoofers', destination: '/drivers/midwoofers/sfcr-midwoofers', permanent: true },
  { source: '/product-category/drivers/woofers/cac-woofers', destination: '/drivers/woofers/cac-woofers', permanent: true },
  { source: '/product-category/family-product', destination: '/drivers', permanent: true },
  { source: '/product-category/family-product/cac-family-product', destination: '/drivers/cac', permanent: true },
  { source: '/product-category/family-product/crc-family-product', destination: '/drivers/crc', permanent: true },
  { source: '/product-category/family-product/mfc-family-product', destination: '/drivers/mfc', permanent: true },
  { source: '/product-category/family-product/nac-family-product', destination: '/drivers/nbac', permanent: true },
  { source: '/product-category/family-product/nrx-family-product', destination: '/drivers/nrx', permanent: true },
  { source: '/product-category/family-product/pac-family-product', destination: '/drivers/pac', permanent: true },
  { source: '/product-category/family-product/pfc-family-product', destination: '/drivers/pfcr', permanent: true },
  { source: '/product-category/family-product/satori-family-product', destination: '/drivers/satori', permanent: true },
  { source: '/product-category/family-product/sfc-family-product', destination: '/drivers/sfc', permanent: true },
  { source: '/product-category/family-product/coaxial-family-product', destination: '/drivers/coaxials', permanent: true },
  { source: '/product-category/kits', destination: '/kits', permanent: true },
  { source: '/product-category/kits-kits', destination: '/kits', permanent: true },
  { source: '/product-category/drivers/tweeters/softtw', destination: '/drivers/tweeters', permanent: true },
  { source: '/product-category/drivers/tweeters/hard', destination: '/drivers/tweeters', permanent: true },
  { source: '/product-category/drivers/widebanders/hard-wideband', destination: '/drivers/widebanders', permanent: true },
  { source: '/product-category/drivers/widebanders/soft-wideband', destination: '/drivers/widebanders', permanent: true },
  { source: '/product-category/drivers/midranges/hard-midrange', destination: '/drivers/midranges', permanent: true },
  { source: '/product-category/drivers/midranges/soft-midrange', destination: '/drivers/midranges', permanent: true },
  { source: '/product-category/drivers/midwoofers/hard-midwoofers', destination: '/drivers/midwoofers', permanent: true },
  { source: '/product-category/drivers/midwoofers/soft-midwoofers', destination: '/drivers/midwoofers', permanent: true },
  { source: '/product-category/drivers/woofers/hard-woofers', destination: '/drivers/woofers', permanent: true },
  { source: '/product-category/drivers/woofers/soft-woofers', destination: '/drivers/woofers', permanent: true },
  { source: '/product-category/drivers/passive-radiators/hard-passive-radiators', destination: '/drivers/passive-radiators', permanent: true },
  { source: '/product-category/drivers/passive-radiators/soft-passive-radiators', destination: '/drivers/passive-radiators', permanent: true },
  { source: '/product-category/coaxials', destination: '/drivers/coaxials', permanent: true },
  { source: '/product-category/drivers/oem/tweeters-oem', destination: '/drivers/oem/tweeters-oem', permanent: true },
  { source: '/product-category/drivers/oem/midranges-oem', destination: '/drivers/oem/midranges-oem', permanent: true },
  { source: '/product-category/drivers/oem/midwoofers-oem', destination: '/drivers/oem/midwoofers-oem', permanent: true },
  { source: '/product-category/drivers/oem/coaxials-oem', destination: '/drivers/oem/coaxials-oem', permanent: true },
  { source: '/product-category/new-products/hard-coming-soon', destination: '/new-products', permanent: true },
  { source: '/product-category/kits/discontinued-kits', destination: '/kits', permanent: true },
  { source: '/product-category/drivers/filler-drivers', destination: '/drivers/midranges/satori-midranges', permanent: true },
  { source: '/product-category/kits/accessories', destination: '/kits/accessories', permanent: true },
  { source: '/product-category/drivers/oem/passive-radiators-oem', destination: '/drivers/oem/passive-radiators-oem', permanent: true },
  { source: '/product-category/drivers/oem/woofers-oem', destination: '/drivers/oem/woofers-oem', permanent: true },
  { source: '/product-category/drivers/oem/nac-midwoofers-oem', destination: '/drivers/oem/nbac-midwoofers-oem', permanent: true },
  { source: '/product-category/drivers/oem/nrx-midwoofers-oem', destination: '/drivers/oem/nrx-midwoofers-oem', permanent: true },
  { source: '/product-category/drivers/oem/pfc-midwoofers-oem', destination: '/drivers/oem/pfcr-midwoofers-oem', permanent: true },
  { source: '/product-category/drivers/oem/satori-midwoofers-oem', destination: '/drivers/oem/satori-midwoofers-oem', permanent: true },
  { source: '/product-category/drivers/oem/shallow-subwoofers-oem', destination: '/drivers/oem/shallow-subwoofers-oem', permanent: true },
  { source: '/product-category/drivers/oem/subwoofers-oem', destination: '/drivers/oem/subwoofers-oem', permanent: true },
  { source: '/product-category/full-range', destination: '/drivers/full-ranges', permanent: true },
  { source: '/product-category/drivers/woofers/sfcl-woofers', destination: '/drivers/woofers/sfcl-woofers', permanent: true },

  //product-sitemap.xml
  { source: '/product/gema', destination: '/products/gema', permanent: true },
  { source: '/product/tifa-8', destination: '/products/tifa-8', permanent: true },
  { source: '/product/tifa-6', destination: '/products/tifa-6', permanent: true },
  { source: '/product/6″-sb17nrx2l35-4-norex', destination: '/products/sb17nrx2l35-4', permanent: true },
  { source: '/product/6″-sb17nrx2l35-8-norex', destination: '/products/sb17nrx2l35-8', permanent: true },
  { source: '/product/8″-sb20pfcs30-7-paper', destination: '/products/sb20pfcs30-7', permanent: true },
  { source: '/product/8″-sb23mfcl-00-polypropylene', destination: '/products/sb23mfcl-00', permanent: true },
  { source: '/product/10-sb26sfcl38-8-paper', destination: '/products/sb26sfcl38-8', permanent: true },
  { source: '/product/10-sb26sfcl38-4-paper', destination: '/products/sb26sfcl38-4', permanent: true },
  { source: '/product/micro', destination: '/products/micro', permanent: true },
  { source: '/product/arya', destination: '/products/arya', permanent: true },
  { source: '/product/rinjani-be', destination: '/products/rinjani-be', permanent: true },
  { source: '/product/rinjani', destination: '/products/rinjani', permanent: true },
  { source: '/product/sb29rdac-c000-4', destination: '/products/sb29rdac-c000-4', permanent: true },
  { source: '/product/sasandu-tx', destination: '/products/sasandu-tx', permanent: true },
  { source: '/product/sasandu', destination: '/products/sasandu', permanent: true },
  { source: '/product/rinjani-tx', destination: '/products/rinjani-tx', permanent: true },
  { source: '/product/bromo', destination: '/products/bromo', permanent: true },
  { source: '/product/ara-tx', destination: '/products/ara-tx', permanent: true },
  { source: '/product/ara-be', destination: '/products/ara-be', permanent: true },
  { source: '/product/ara', destination: '/products/ara', permanent: true },
  { source: '/product/4-sb12pfcr25-8-paper', destination: '/products/sb12pfcr25-8', permanent: true },
  { source: '/product/4-sb12pfcr25-4-paper', destination: '/products/sb12pfcr25-4', permanent: true },
  { source: '/product/sb14st-c000-4', destination: '/products/sb14st-c000-4', permanent: true },
  { source: '/product/5x8in-sb15sfcr39-4', destination: '/products/sb15sfcr39-4', permanent: true },
  { source: '/product/95-satori-wo24tx-8-textreme', destination: '/products/wo24tx-8', permanent: true },
  { source: '/product/95-satori-wo24tx-4-textreme', destination: '/products/wo24tx-4', permanent: true },
  { source: '/product/5-satori-mr13tx-4-textreme', destination: '/products/mr13tx-4', permanent: true },
  { source: '/product/6½-satori-mr16tx-8-textreme', destination: '/products/mr16tx-8', permanent: true },
  { source: '/product/sb29sdnc-c000-4-fabric', destination: '/products/sb29sdnc-c000-4', permanent: true },
  { source: '/product/10″-sw26sfc38-8-paper', destination: '/products/sw26sfc38-8', permanent: true },
  { source: '/product/4-sb12pacr25-4-coax', destination: '/products/sb12pacr25-4-coax', permanent: true },
  { source: '/product/10-sw26sfc38-4-paper', destination: '/products/sw26sfc38-4', permanent: true },
  { source: '/product/at60nc-4-kapton', destination: '/products/at60nc-4', permanent: true },
  { source: '/product/12-sb34nrx2-00-norex', destination: '/products/sb34nrx2-00', permanent: true },
  { source: '/product/10-sb29nrx2-00-norex', destination: '/products/sb29nrx2-00', permanent: true },
  { source: '/product/satori-tw29txnwg-4-textreme', destination: '/products/tw29txnwg-4', permanent: true },
  { source: '/product/7½in-satori-mw19pnw-8', destination: '/products/mw19pnw-8', permanent: true },
  { source: '/product/7½in-satori-mw19pnw-4', destination: '/products/mw19pnw-4', permanent: true },
  { source: '/product/10in-sw26dbac-00', destination: '/products/sw26dbac-00', permanent: true },
  { source: '/product/10in-sb29nrx-00-norex', destination: '/products/sb29nrx-00', permanent: true },
  { source: '/product/12in-sb34nrx-00-norex', destination: '/products/sb34nrx-00', permanent: true },
  { source: '/product/dw50', destination: '/products/dw50', permanent: true },
  { source: '/product/6in-sb16pfcr-00-paper', destination: '/products/sb16pfcr-00', permanent: true },
  { source: '/product/5x8in-sb15sfcr-00', destination: '/products/sb15sfcr-00', permanent: true },
  { source: '/product/4-sb12pacr-00-aluminium', destination: '/products/sb12pacr-00', permanent: true },
  { source: '/product/4-sb12pfcr-00-paper', destination: '/products/sb12pfcr-00', permanent: true },
  { source: '/product/5-sb13pfcr-00-paper', destination: '/products/sb13pfcr-00', permanent: true },
  { source: '/product/6-sb20pfcr-00-paper', destination: '/products/sb20pfcr-00', permanent: true },
  { source: '/product/5in-sb13pfc25-4-coax-paper', destination: '/products/sb13pfc25-4-coax', permanent: true },
  { source: '/product/6in-sb16pfc25-4-coax-paper', destination: '/products/sb16pfc25-4-coax', permanent: true },
  { source: '/product/4in-sb12pac-00-aluminium', destination: '/products/sb12pac-00', permanent: true },
  { source: '/product/10in-sw26dac-00', destination: '/products/sw26dac-00', permanent: true },
  { source: '/product/4-sb12pfc-00-paper', destination: '/products/sb12pfc-00', permanent: true },
  { source: '/product/5-sb13pfc-00-paper', destination: '/products/sb13pfc-00', permanent: true },
  { source: '/product/6-sb16pfc-00-paper', destination: '/products/sb16pfc-00', permanent: true },
  { source: '/product/8-sb20pfc-00-paper', destination: '/products/sb20pfc-00', permanent: true },
  { source: '/product/10in-sw26dac76-4', destination: '/products/sw26dac76-4', permanent: true },
  { source: '/product/10in-sw26dac76-8', destination: '/products/sw26dac76-8', permanent: true },
  { source: '/product/10in-sw26dac76-3-dv', destination: '/products/sw26dac76-3-dv', permanent: true },
  { source: '/product/10in-sw26dbac76-3-dv', destination: '/products/sw26dbac76-3-dv', permanent: true },
  { source: '/product/12in-sb34swpl76-3-dv', destination: '/products/sb34swpl76-3-dv', permanent: true },
  { source: '/product/8in-sb23nacs45-4', destination: '/products/sb23nacs45-4', permanent: true },
  { source: '/product/8in-sb23nacs45-8', destination: '/products/sb23nacs45-8', permanent: true },
  { source: '/product/8-sb20pfc30-4-paper', destination: '/products/sb20pfc30-4', permanent: true },
  { source: '/product/8-sb20pfc30-8-paper', destination: '/products/sb20pfc30-8', permanent: true },
  { source: '/product/7½″-satori-mw19pf-4-paper-2', destination: '/products/mw19pf-8', permanent: true },
  { source: '/product/7½″-satori-mw19pf-4-paper', destination: '/products/mw19pf-4', permanent: true },
  { source: '/product/6½-satori-mw16pf-8-paper', destination: '/products/mw16pf-8', permanent: true },
  { source: '/product/6½-satori-mw16pf-4-paper', destination: '/products/mw16pf-4', permanent: true },
  { source: '/product/6in-sb16pfc25-8-paper', destination: '/products/sb16pfc25-8', permanent: true },
  { source: '/product/6in-sb16pfc25-4-paper', destination: '/products/sb16pfc25-4', permanent: true },
  { source: '/product/5in-sb13pfc25-8-paper', destination: '/products/sb13pfc25-8', permanent: true },
  { source: '/product/5in-sb13pfc25-4-paper', destination: '/products/sb13pfc25-4', permanent: true },
  { source: '/product/4in-sb12pfc25-8-paper', destination: '/products/sb12pfc25-8', permanent: true },
  { source: '/product/4in-sb12pfc25-4-paper', destination: '/products/sb12pfc25-4', permanent: true },
  { source: '/product/6in-sb17nrxc35-8', destination: '/products/sb17nrxc35-8', permanent: true },
  { source: '/product/6in-sb17nrxc35-4', destination: '/products/sb17nrxc35-4', permanent: true },
  { source: '/product/5in-sb15nrxc30-8', destination: '/products/sb15nrxc30-8', permanent: true },
  { source: '/product/5in-sb15nrxc30-4', destination: '/products/sb15nrxc30-4', permanent: true },
  { source: '/product/6in-sb17nac35-8', destination: '/products/sb17nac35-8', permanent: true },
  { source: '/product/6in-sb17nac35-4', destination: '/products/sb17nac35-4', permanent: true },
  { source: '/product/5in-sb15nac30-4', destination: '/products/sb15nac30-4', permanent: true },
  { source: '/product/5in-sb15nac30-8', destination: '/products/sb15nac30-8', permanent: true },
  { source: '/product/4in-sb12mnrx25-4-paper', destination: '/products/sb12mnrx25-4', permanent: true },
  { source: '/product/sb29rdc-c000-4-fabric', destination: '/products/sb29rdc-c000-4', permanent: true },
  { source: '/product/sb26stc-c000-4', destination: '/products/sb26stc-c000-4', permanent: true },
  { source: '/product/7½-satori-mt19cp-8-paper', destination: '/products/mt19cp-8', permanent: true },
  { source: '/product/9½in-satori-wo24p-8', destination: '/products/wo24p-8', permanent: true },
  { source: '/product/9½in-satori-wo24p-4', destination: '/products/wo24p-4', permanent: true },
  { source: '/product/7½-satori-mw19tx-8-textreme', destination: '/products/mw19tx-8', permanent: true },
  { source: '/product/7½-satori-mw19tx-4-textreme', destination: '/products/mw19tx-4', permanent: true },
  { source: '/product/6-5-satori-mw16tx-8-textreme', destination: '/products/mw16tx-8', permanent: true },
  { source: '/product/6-5-satori-mw16tx-4-textreme', destination: '/products/mw16tx-4', permanent: true },
  { source: '/product/eka', destination: '/products/eka', permanent: true },
  { source: '/product/micro-c', destination: '/products/micro-c', permanent: true },
  { source: '/product/4in-sb12nrxf25-8-norex', destination: '/products/sb12nrxf25-8', permanent: true },
  { source: '/product/4in-sb12nrxf25-4-norex', destination: '/products/sb12nrxf25-4', permanent: true },
  { source: '/product/6-sb16pfcr25-4-coax', destination: '/products/sb16pfcr25-4-coax', permanent: true },
  { source: '/product/5-sb13pfcr25-4-coax', destination: '/products/sb13pfcr25-4-coax', permanent: true },
  { source: '/product/4-sb12pfcr25-4-coax', destination: '/products/sb12pfcr25-4-coax', permanent: true },
  { source: '/product/10in-sw26dbac76-8', destination: '/products/sw26dbac76-8', permanent: true },
  { source: '/product/10in-sw26dbac76-4', destination: '/products/sw26dbac76-4', permanent: true },
  { source: '/product/15in-sb42fhcl75-6', destination: '/products/sb42fhcl75-6', permanent: true },
  { source: '/product/12in-sb34swpl76-4', destination: '/products/sb34swpl76-4', permanent: true },
  { source: '/product/12in-sb34swnrx-s75-6-norex', destination: '/products/sb34swnrx-s75-6', permanent: true },
  { source: '/product/10in-sb29swnrx-s75-6-norex', destination: '/products/sb29swnrx-s75-6', permanent: true },
  { source: '/product/8in-sb23mfcl45-8', destination: '/products/sb23mfcl45-8', permanent: true },
  { source: '/product/8in-sb23mfcl45-4', destination: '/products/sb23mfcl45-4', permanent: true },
  { source: '/product/8in-sb23nbacs45-8', destination: '/products/sb23nbacs45-8', permanent: true },
  { source: '/product/8in-sb23nbacs45-4', destination: '/products/sb23nbacs45-4', permanent: true },
  { source: '/product/12-sb34nrxl75-8-norex', destination: '/products/sb34nrxl75-8', permanent: true },
  { source: '/product/12-sb34nrx75-16-norex', destination: '/products/sb34nrx75-16', permanent: true },
  { source: '/product/10-sb29nrx75-8-norex', destination: '/products/sb29nrx75-8', permanent: true },
  { source: '/product/10-sb29nrx75-6-norex', destination: '/products/sb29nrx75-6', permanent: true },
  { source: '/product/12-sb34nrx75-6-norex', destination: '/products/sb34nrx75-6', permanent: true },
  { source: '/product/8in-sb23nrxs45-8-norex', destination: '/products/sb23nrxs45-8', permanent: true },
  { source: '/product/8-sb23nrxs45-4-norex', destination: '/products/sb23nrxs45-4', permanent: true },
  { source: '/product/8-sb20pfcr30-8-paper', destination: '/products/sb20pfcr30-8', permanent: true },
  { source: '/product/8-sb20pfcr30-4-paper', destination: '/products/sb20pfcr30-4', permanent: true },
  { source: '/product/8in-sb23cacs45-8', destination: '/products/sb23cacs45-8', permanent: true },
  { source: '/product/8in-sb23cacs45-4', destination: '/products/sb23cacs45-4', permanent: true },
  { source: '/product/5x8in-sb15sfcr39-8', destination: '/products/sb15sfcr39-8', permanent: true },
  { source: '/product/7½in-satori-mw19p-8', destination: '/products/mw19p-8', permanent: true },
  { source: '/product/6½in-satori-mw16pnw-8', destination: '/products/mw16pnw-8', permanent: true },
  { source: '/product/6½in-satori-mw16pnw-4', destination: '/products/mw16pnw-4', permanent: true },
  { source: '/product/6½in-satori-mw16p-8', destination: '/products/mw16p-8', permanent: true },
  { source: '/product/6½in-satori-mw16p-4', destination: '/products/mw16p-4', permanent: true },
  { source: '/product/5-satori-mw13pnw-8', destination: '/products/mw13pnw-8', permanent: true },
  { source: '/product/5in-satori-mw13pnw-4', destination: '/products/mw13pnw-4', permanent: true },
  { source: '/product/5in-satori-mw13p-8', destination: '/products/mw13p-8', permanent: true },
  { source: '/product/5in-satori-mw13p-4', destination: '/products/mw13p-4', permanent: true },
  { source: '/product/5-satori-mw13tx-8-textreme', destination: '/products/mw13tx-8', permanent: true },
  { source: '/product/5-satori-mw13tx-4-textreme', destination: '/products/mw13tx-4', permanent: true },
  { source: '/product/6-sb16pfcr25-8-paper', destination: '/products/sb16pfcr25-8', permanent: true },
  { source: '/product/6-sb16pfcr25-4-paper', destination: '/products/sb16pfcr25-4', permanent: true },
  { source: '/product/5-sb13pfcr25-8-paper', destination: '/products/sb13pfcr25-8', permanent: true },
  { source: '/product/5-sb13pfcr25-4-paper', destination: '/products/sb13pfcr25-4', permanent: true },
  { source: '/product/4-sb12pacr25-4-aluminum', destination: '/products/sb12pacr25-4', permanent: true },
  { source: '/product/4in-sb12pac25-4', destination: '/products/sb12pac25-4', permanent: true },
  { source: '/product/6in-sb17nrx2c35-8-norex', destination: '/products/sb17nrx2c35-8', permanent: true },
  { source: '/product/6in-sb17nrx2c35-4-norex', destination: '/products/sb17nrx2c35-4', permanent: true },
  { source: '/product/5in-sb15nrx2c30-8-norex', destination: '/products/sb15nrx2c30-8', permanent: true },
  { source: '/product/5in-sb15nrx2c30-4-norex', destination: '/products/sb15nrx2c30-4', permanent: true },
  { source: '/product/4in-sb12nrx25-8-norex', destination: '/products/sb12nrx25-8', permanent: true },
  { source: '/product/4in-sb12nrx25-4-norex', destination: '/products/sb12nrx25-4', permanent: true },
  { source: '/product/6in-sb17nbac35-8', destination: '/products/sb17nbac35-8', permanent: true },
  { source: '/product/6in-sb17nbac35-4', destination: '/products/sb17nbac35-4', permanent: true },
  { source: '/product/5in-sb15nbac30-8', destination: '/products/sb15nbac30-8', permanent: true },
  { source: '/product/5in-sb15nbac30-4', destination: '/products/sb15nbac30-4', permanent: true },
  { source: '/product/6in-sb17mfc35-8', destination: '/products/sb17mfc35-8', permanent: true },
  { source: '/product/6in-sb17mfc35-4', destination: '/products/sb17mfc35-4', permanent: true },
  { source: '/product/5in-sb15mfc30-8', destination: '/products/sb15mfc30-8', permanent: true },
  { source: '/product/5in-sb15mfc30-4', destination: '/products/sb15mfc30-4', permanent: true },
  { source: '/product/6in-sb17crc35-8', destination: '/products/sb17crc35-8', permanent: true },
  { source: '/product/6in-sb17crc35-4', destination: '/products/sb17crc35-4', permanent: true },
  { source: '/product/5-sb15crc30-8-carbon', destination: '/products/sb15crc30-8', permanent: true },
  { source: '/product/6-sb15crc30-4-carbon', destination: '/products/sb15crc30-4', permanent: true },
  { source: '/product/6in-sb17cac35-8', destination: '/products/sb17cac35-8', permanent: true },
  { source: '/product/6in-sb17cac35-4', destination: '/products/sb17cac35-4', permanent: true },
  { source: '/product/5in-sb15cac30-8', destination: '/products/sb15cac30-8', permanent: true },
  { source: '/product/5in-sb15cac30-4', destination: '/products/sb15cac30-4', permanent: true },
  { source: '/product/4in-sb12cacs25-8', destination: '/products/sb12cacs25-8', permanent: true },
  { source: '/product/4in-sb12cacs25-4', destination: '/products/sb12cacs25-4', permanent: true },
  { source: '/product/6½in-satori-mr16pnw-8', destination: '/products/mr16pnw-8', permanent: true },
  { source: '/product/6½in-satori-mr16pnw-4', destination: '/products/mr16pnw-4', permanent: true },
  { source: '/product/6½in-satori-mr16p-8', destination: '/products/mr16p-8', permanent: true },
  { source: '/product/6½in-satori-mr16p-4', destination: '/products/mr16p-4', permanent: true },
  { source: '/product/4-sb12mnrx2-25-4-norex', destination: '/products/sb12mnrx2-25-4', permanent: true },
  { source: '/product/2-5in-satori-md60n-6-fabric', destination: '/products/md60n-6', permanent: true },
  { source: '/product/sb26stac-c000-4', destination: '/products/sb26stac-c000-4', permanent: true },
  { source: '/product/7½in-satori-mw19p-4-2', destination: '/products/mw19p-4', permanent: true },
  { source: '/product/5in-satori-mr13p-4', destination: '/products/mr13p-4', permanent: true },
  { source: '/product/5-satori-mr13p-8', destination: '/products/mr13p-8', permanent: true },
  { source: '/product/5-satori-mr13pnw-4', destination: '/products/mr13pnw-4', permanent: true },
  { source: '/product/5-satori-mr13pnw-8', destination: '/products/mr13pnw-8', permanent: true },
  { source: '/product/1in-sb36wbac21-8', destination: '/products/sb36wbac21-8', permanent: true },
  { source: '/product/2-5in-sb65wbac25-4', destination: '/products/sb65wbac25-4', permanent: true },
  { source: '/product/3in-sb10pgc21-4', destination: '/products/sb10pgc21-4', permanent: true },
  { source: '/product/1-sb36wbac21-4-aluminum', destination: '/products/sb36wbac21-4', permanent: true },
  { source: '/product/satori-tw29bn-b', destination: '/products/tw29bn-b', permanent: true },
  { source: '/product/satori-tw29r', destination: '/products/tw29r', permanent: true },
  { source: '/product/satori-tw29r-b', destination: '/products/tw29r-b', permanent: true },
  { source: '/product/satori-tw29rn', destination: '/products/tw29rn', permanent: true },
  { source: '/product/satori-tw29rn-b', destination: '/products/tw29rn-b', permanent: true },
  { source: '/product/satori-tw29dn', destination: '/products/tw29dn', permanent: true },
  { source: '/product/satori-tw29dn-8', destination: '/products/tw29dn-8', permanent: true },
  { source: '/product/satori-tw29dn-b', destination: '/products/tw29dn-b', permanent: true },
  { source: '/product/satori-tw29dn-b-8', destination: '/products/tw29dn-b-8', permanent: true },
  { source: '/product/satori-tw29txn-b-textreme', destination: '/products/tw29txn-b', permanent: true },
  { source: '/product/satori-twbn-8', destination: '/products/tw29bn-8', permanent: true },
  { source: '/product/satori-tw29bn-b-8', destination: '/products/tw29bn-b-8', permanent: true },
  { source: '/product/satori-tw29rn-8', destination: '/products/tw29rn-8', permanent: true },
  { source: '/product/satori-tw29rn-b-8', destination: '/products/tw29rn-b-8', permanent: true },
  { source: '/product/satori-tw29d-fabric', destination: '/products/tw29d', permanent: true },
  { source: '/product/satori-tw29d-b-fabric', destination: '/products/tw29d-b', permanent: true },
  { source: '/product/satori-tw29txn-b-8-textreme', destination: '/products/tw29txn-b-8', permanent: true },
  { source: '/product/satori-tw29bnwg-4-beryllium', destination: '/products/tw29bnwg-4', permanent: true },
  { source: '/product/satori-tw29bnwg-8-beryllium', destination: '/products/tw29bnwg-8', permanent: true },
  { source: '/product/sb21rdc-c000-4', destination: '/products/sb21rdc-c000-4', permanent: true },
  { source: '/product/sb29rdnc-c000-4', destination: '/products/sb29rdnc-c000-4', permanent: true },
  { source: '/product/sb21rdcn-c000-4', destination: '/products/sb21rdcn-c000-4', permanent: true },
  { source: '/product/sb19st-c000-4', destination: '/products/sb19st-c000-4', permanent: true },
  { source: '/product/sb21sdc-c000-4', destination: '/products/sb21sdc-c000-4', permanent: true },
  { source: '/product/sb26st-c000-5', destination: '/products/sb26st-c000-5', permanent: true },
  { source: '/product/sb26stcn-c000-4', destination: '/products/sb26stcn-c000-4', permanent: true },
  { source: '/product/sb26adc-c000-4', destination: '/products/sb26adc-c000-4', permanent: true },
  { source: '/product/sb29sdac-c000-4', destination: '/products/sb29sdac-c000-4', permanent: true },
  { source: '/product/sb26cdc-c000-4', destination: '/products/sb26cdc-c000-4', permanent: true },
  { source: '/product/sb29bac-c000-4', destination: '/products/sb29bac-c000-4', permanent: true },
  { source: '/product/sb29bnc-c000-4', destination: '/products/sb29bnc-c000-4', permanent: true },
  { source: '/product/sb26stwgc-4-fabric', destination: '/products/sb26stwgc-4', permanent: true },
  { source: '/product/sb21sdcn-c000-4', destination: '/products/sb21sdcn-c000-4', permanent: true },
  { source: '/product/satori-24-magnetic-grille', destination: '/products/24-magnetic-grille', permanent: true },
  { source: '/product/satori-tw29bn', destination: '/products/tw29bn', permanent: true },
  { source: '/product/satori-tw29b', destination: '/products/tw29b', permanent: true },
  { source: '/product/satori-19-magnetic-grille', destination: '/products/19-magnetic-grille', permanent: true },
  { source: '/product/satori-16-magnetic-grille', destination: '/products/16-magnetic-grille', permanent: true },
  { source: '/product/satori-13-magnetic-grille', destination: '/products/13-magnetic-grille', permanent: true },
  { source: '/product/satori-tw29-magnetic-grille', destination: '/products/tweeter-magnetic-grille', permanent: true },
  { source: '/product/satori-tw29b-b', destination: '/products/tw29b-b', permanent: true },
];

// Generate redirects for each locale
const localizedRedirects = [];

for (const { source, destination, permanent } of baseRedirects) {
  localizedRedirects.push({
    source: `${source}`,
    destination: `${destination}`,
    permanent,
  })
}

module.exports = localizedRedirects;